---
- name: Config Web VM with Docker
  hosts: webservers
  become: true
  tasks:

  - name: docker.io
    apt:
      force_apt_get: yes
      name: docker.io
      state: present

  - name: Install pip
    apt: 
      force_apt_get: yes
      name: python-pip
      state: present

  - name: Install Docker python module
    pip:
      name: docker
      state: present

  - name: download and launch a docker web container
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      published_ports: 80:80
- name: Configure Elk VM with Docker
  hosts: elkservers
  remote_user: ghuls
  become: true
  tasks:

    # Use apt module
    - name: Install docker.io
      apt:
        force_apt_get: yes
        name: docker.io
        state: present

      # Use apt module
    - name: Install pip
      apt:
        force_apt_get: yes
        name: python-pip
        state: present

      # Use pip module
    - name: Install Docker python module
      pip:
        name: docker
        state: present

      # Use command module
    - name: Increase virtual memory
      command: sysctl -w vm.max_map_count=262144

      # Use docker_container module
    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk
        state: started
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

      # Pause for 2 minutes to build app cache.
    - name: Pause to allow Elk Container to establish necessary Kibana headers
      pause:
        minutes: 2
- name: Installing and Launch Filebeat
  hosts: webservers
  become: yes
  tasks:
    # Use command module 
  - name: Download filebeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

    # Use command module
  - name: Install filebeat .deb
    command: dpkg -i filebeat-7.4.0-amd64.deb

    # Use copy module
  - name: Drop in filebeat.yml
    copy:
      src: ./Filebeat_Configuration.yml
      dest: /etc/filebeat/filebeat.yml
    
    # Use command module
  - name: Enable and Configure System Module
    command: filebeat modules enable system
    
    # Use command module
  - name: Setup filebeat
    command: filebeat setup
    
    # Use command module
  - name: Start filebeat service
    command: service filebeat start
- name: Install metric beat
  hosts: webservers
  become: true
  tasks:

    # Use command module
  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

    # Use command module
  - name: install metricbeat
    command: dpkg -i metricbeat-7.4.0-amd64.deb

    # Use copy module
  - name: drop in metricbeat config
    copy:
      src: ./Metricbeat_Configuration.yml
      dest: /etc/metricbeat/metricbeat.yml

    # Use command module
  - name: enable and configure docker module for metric beat
    command: metricbeat modules enable docker

    # Use command module
  - name: setup metric beat
    command: metricbeat setup

    # Use command module
  - name: start metric beat
    command: service metricbeat start